    drop table book if exists;

    drop table basket if exists;

    drop table basket_books if exists;

    create table book (
        id bigint generated by default as identity,
        version bigint not null,
        title varchar(255) not null,
        author varchar(255) not null,
        price double not null,
        quantity integer not null,
        date_created timestamp not null,
        date_updated timestamp not null,
        primary key (id)
    );

    create table basket (
        id bigint generated by default as identity,
        version bigint not null,
        user_id bigint,
        total_price decimal,
        date_created timestamp not null,
        date_updated timestamp not null,
        primary key (id)
    );
    
     create table basket_books (
        id bigint generated by default as identity,
        version bigint not null,
        book_id bigint not null,
        basket_id bigint not null,
        quantity integer not null,
        primary key (id)
    );

     alter table basket_books
        add constraint FK_basket_books_book
        foreign key (book_id)
        references book;
        
      alter table basket_books
        add constraint FK_basket_books_basket
        foreign key (basket_id)
        references basket;
        
        